// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240821092342-aa2316bb6983 DO NOT EDIT.
package models

// Test A test object
type Test struct {
	// Message A message
	Message string `json:"message"`
}
